### ISSUE TITLE
Real Estate Listings

### ISSUE THREAD

**Issue by DevCEDTeam** [DevCEDTeam/CED#170]
Git Rep 

[classified-ai-agent.zip](https://github.com/user-attachments/files/19412189/classified-ai-agent.zip)

**Comment by DevCEDTeam** [comment]
Absolutely — here is your **updated and GitHub-ready Markdown export** of the **Classified AI Agent Project** with proper formatting, syntax highlighting, and copyable code sections for easy pasting into a `README.md` or Notion wiki.

---

# 📦 Classified AI Agent — GitHub Export Package

---

## **1. Project Directory Structure**

```graphql
classified-ai-agent/
├── backend/                     # FastAPI backend
│   ├── main.py
│   ├── config.py
│   ├── requirements.txt
│   ├── api/
│   │   ├── auth.py
│   │   ├── generate.py
│   │   ├── signal.py
│   │   ├── bot.py
│   ├── services/
│   │   ├── firebase.py
│   │   ├── vertexai.py
│   │   ├── content.py
│   │   ├── poster_runner.py
│   ├── utils/
│   │   ├── jwt_auth.py
│   │   ├── demographics.py
│
├── shiny_ui/                   # Shiny for Python frontend
│   ├── app.py
│   ├── requirements.txt
│   ├── components/
│   │   ├── login_form.py
│   │   ├── dashboard.py
│   │   ├── chatbot.py
│   │   ├── billing.py
│   │   ├── history.py
│   │   ├── analytics.py
│   │   ├── admin.py
│
├── poster_bot/                 # Pyppeteer2 headless bot
│   ├── main.py
│   ├── fb_poster.py
│   ├── firestore.py
│   ├── requirements.txt
│   ├── cookies.json            # Use Secret Manager in production
│
├── cloud_functions/           # Firestore-triggered poster (optional)
│   └── firestore_trigger/
│       ├── main.py
│       ├── fb_poster.py
│       ├── firestore_utils.py
│       └── requirements.txt
│
├── terraform/                 # Terraform for GCP infra
│   ├── main.tf
│   ├── variables.tf
│   ├── outputs.tf
│   ├── project.tf
│   ├── iam.tf
│   ├── firestore.tf
│   ├── storage.tf
│   ├── cloudrun.tf
│   ├── scheduler.tf
│   ├── dns.tf
│   ├── vertexai.tf
│   └── firestore.rules
│
├── .github/
│   └── workflows/
│       └── deploy.yml         # GitHub Actions CI/CD
│
├── Dockerfile                 # Unified build for Shiny + FastAPI
├── .env.sample                # Env config
├── .gcloudignore
├── .gitignore
├── README.md
```

---

## **2. GitHub Project Setup – Developer Instructions**

### 🧱 A. Clone and Setup Locally

```bash
git clone https://github.com/YOUR_ORG/classified-ai-agent.git
cd classified-ai-agent

cp .env.sample .env
```

🔐 Update `.env` with real credentials:

- `FIREBASE_CREDENTIALS`
- `STRIPE_SECRET_KEY`
- `JWT_SECRET_KEY`
- etc.

---

### ⚙️ B. Backend (FastAPI)

```bash
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
```

---

### 🎛️ C. Frontend (Shiny)

```bash
cd shiny_ui
pip install -r requirements.txt
shiny run --app-dir .
```

---

### 🤖 D. Poster Bot (Headless Automation)

```bash
cd poster_bot
pip install -r requirements.txt
python main.py
```

---

### ☁️ E. GCP Deployment via Terraform

```bash
cd terraform
terraform init
terraform apply
```

⚠️ Make sure you have GCP IAM, billing, Firestore, and Firebase enabled.

---

### 🐳 F. Build Docker for Production

```bash
gcloud builds submit --tag gcr.io/YOUR_PROJECT_ID/classified-ai-agent
gcloud run deploy classified-ai-agent \
  --image gcr.io/YOUR_PROJECT_ID/classified-ai-agent \
  --platform managed \
  --region us-central1 \
  --allow-unauthenticated
```

---

## **3. GitHub Repository Initialization**

```bash
git init
git add .
git commit -m "Initial commit"
git remote add origin https://github.com/YOUR_ORG/classified-ai-agent.git
git push -u origin main
```

---

## **4. GitHub Actions CI/CD**
📄 `.github/workflows/deploy.yml`

```yaml
name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/classified-ai-agent:$GITHUB_SHA .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/classified-ai-agent:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy classified-ai-agent \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/classified-ai-agent:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
```

---

## **5. `.env.sample` Template**

```env
PROJECT_ID=market-cfored-placeholder
FIREBASE_CREDENTIALS=firebase-service-account.json
STRIPE_SECRET_KEY=sk_test_...
STRIPE_PUBLISHABLE_KEY=pk_test_...
STRIPE_DEFAULT_PRICE_ID=price_...
JWT_SECRET_KEY=your_jwt_key_here
FIREBASE_API_KEY=your_firebase_web_api_key
BACKEND_URL=https://market.cfored.com
```

---

## ✅ Next Steps

Would you like me to:

- 📦 Package and upload the latest `.zip` again?  
- 🔐 Generate GitHub secrets JSON for Cloud Run deploy via `gcloud iam service-accounts keys create`?  
- 📓 Format this into a Notion or Confluence-friendly doc?

Let me know and I’ll finalize the GitHub developer toolkit!
