### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by DevCEDTeam** [DevCEDTeam/CED#35]

**Comment by DevCEDTeam** [comment]
To connect Mautic to Google Cloud Gmail API, you can follow the steps below:

Enable Gmail API: First, you need to enable the Gmail API in your Google Cloud Console.

Set up OAuth2 credentials: To access the Gmail API, you need to set up OAuth2 credentials in Google Cloud Console.

Configure Mautic: In Mautic, go to Configuration > Email Settings and set up an SMTP connection to Gmail. Use the OAuth2 credentials you generated in step 2.

Test your connection: Once you've set up the connection, you can test it by sending a test email from Mautic.

Note that if you're not comfortable doing this yourself, you may want to consult with a developer or IT professional who can assist you with the setup.

**Comment by DevCEDTeam** [comment]
4. Configure your application's security.yml:
   - Open the `app/config/security.yml` file.
   - Add the following configuration for the FOSOAuthServerBundle:
     ```yaml
     security:
         firewalls:
             oauth_token:
                 pattern:    ^/oauth/v2/token
                 security:   false
     
             oauth_authorize:
                 pattern:    ^/oauth/v2/auth
                 # Add your favorite authentication process here
     
             api:
                 pattern:    ^/api
                 fos_oauth:  true
                 stateless:  true
                 anonymous:  false # can be omitted as its default value
     
         access_control:
             - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY] }
     ```
     Note: Adjust the firewall patterns (`^/oauth/v2/token`, `^/oauth/v2/auth`, `^/api`) and access control as per your project's requirements.

5. Configure FOSOAuthServerBundle:
   - Open the `app/config/routing.yml` file.
   - Import the routing configuration for the FOSOAuthServerBundle:
     ```yaml
     # app/config/routing.yml
     fos_oauth_server_token:
         resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
     
     fos_oauth_server_authorize:
         resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
     ```

   - Open the `app/config/config.yml` file.
   - Add the FOSOAuthServerBundle configuration:
    Certainly! Here's the continuation of the configuration steps:

     # app/config/config.yml
     fos_oauth_server:
         db_driver: orm # or pdo_mysql if you use MySQL
         client_class: YourBundle\Entity\Client
         access_token_class: YourBundle\Entity\AccessToken
         refresh_token_class: YourBundle\Entity\RefreshToken
         auth_code_class: YourBundle\Entity\AuthCode
         service:
             user_provider: fos_user.user_provider.username_email

6. Generate the database tables:
   - Run the following command to generate the necessary database tables for the OAuth server:
     ```shell
     php bin/console doctrine:schema:update --force
     ```

7. Create the Gmail API client:
   - Go to the Google Cloud Console (https://console.cloud.google.com/).
   - Create a new project or select an existing one.
   - Enable the Gmail API for your project.
   - Create API credentials (OAuth 2.0 client ID) for your project.
   - Download the JSON file containing the client credentials.

8. Configure the Gmail API client credentials:
   - Rename the downloaded JSON file to `client_secret.json`.
   - Move the `client_secret.json` file to the `app/` directory of your Symfony project.

9. Configure the Gmail API integration:
   - Open the `app/config/config.yml` file.
   - Add the following configuration for the Gmail API:
     ```yaml
     # app/config/config.yml
     google_api:
         client_id: Your_Client_ID
         client_secret: Your_Client_Secret
         redirect_uri: Your_Redirect_URI
         scopes:
             - https://www.googleapis.com/auth/gmail.send
     ```
     Replace `Your_Client_ID`, `Your_Client_Secret`, and `Your_Redirect_URI` with the corresponding values from the client credentials you obtained in step 7.

10. Implement the Gmail API integration:
    - In your Symfony project, create a service or class responsible for handling the Gmail API integration.
    - Use the Gmail API client library (such as `google/apiclient`) to authenticate and send emails via the Gmail API.
    - Follow the Gmail API documentation and library documentation to implement the necessary logic for sending outbound emails.

11. Test the integration:
    - Create a test route or controller action to trigger the email sending functionality.
    - Make a request to the test route and verify that the emails are being sent successfully using the Gmail API.

Remember to adjust the configurations and code examples according to your specific Symfony project structure and requirements.


.

**Comment by DevCEDTeam** [comment]
4. Configure your application's security.yml:
   - Open the `app/config/security.yml` file.
   - Add the following configuration for the FOSOAuthServerBundle:
     ```yaml
     security:
         firewalls:
             oauth_token:
                 pattern:    ^/oauth/v2/token
                 security:   false
     
             oauth_authorize:
                 pattern:    ^/oauth/v2/auth
                 # Add your favorite authentication process here
     
             api:
                 pattern:    ^/api
                 fos_oauth:  true
                 stateless:  true
                 anonymous:  false # can be omitted as its default value
     
         access_control:
             - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY] }
     ```
     Note: Adjust the firewall patterns (`^/oauth/v2/token`, `^/oauth/v2/auth`, `^/api`) and access control as per your project's requirements.

5. Configure FOSOAuthServerBundle:
   - Open the `app/config/routing.yml` file.
   - Import the routing configuration for the FOSOAuthServerBundle:
     ```yaml
     # app/config/routing.yml
     fos_oauth_server_token:
         resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
     
     fos_oauth_server_authorize:
         resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
     ```

   - Open the `app/config/config.yml` file.
   - Add the FOSOAuthServerBundle configuration:
    Certainly! Here's the continuation of the configuration steps:

     # app/config/config.yml
     fos_oauth_server:
         db_driver: orm # or pdo_mysql if you use MySQL
         client_class: YourBundle\Entity\Client
         access_token_class: YourBundle\Entity\AccessToken
         refresh_token_class: YourBundle\Entity\RefreshToken
         auth_code_class: YourBundle\Entity\AuthCode
         service:
             user_provider: fos_user.user_provider.username_email

6. Generate the database tables:
   - Run the following command to generate the necessary database tables for the OAuth server:
     ```shell
     php bin/console doctrine:schema:update --force
     ```

7. Create the Gmail API client:
   - Go to the Google Cloud Console (https://console.cloud.google.com/).
   - Create a new project or select an existing one.
   - Enable the Gmail API for your project.
   - Create API credentials (OAuth 2.0 client ID) for your project.
   - Download the JSON file containing the client credentials.

8. Configure the Gmail API client credentials:
   - Rename the downloaded JSON file to `client_secret.json`.
   - Move the `client_secret.json` file to the `app/` directory of your Symfony project.

9. Configure the Gmail API integration:
   - Open the `app/config/config.yml` file.
   - Add the following configuration for the Gmail API:
     ```yaml
     # app/config/config.yml
     google_api:
         client_id: Your_Client_ID
         client_secret: Your_Client_Secret
         redirect_uri: Your_Redirect_URI
         scopes:
             - https://www.googleapis.com/auth/gmail.send
     ```
     Replace `Your_Client_ID`, `Your_Client_Secret`, and `Your_Redirect_URI` with the corresponding values from the client credentials you obtained in step 7.

10. Implement the Gmail API integration:
    - In your Symfony project, create a service or class responsible for handling the Gmail API integration.
    - Use the Gmail API client library (such as `google/apiclient`) to authenticate and send emails via the Gmail API.
    - Follow the Gmail API documentation and library documentation to implement the necessary logic for sending outbound emails.

11. Test the integration:
    - Create a test route or controller action to trigger the email sending functionality.
    - Make a request to the test route and verify that the emails are being sent successfully using the Gmail API.

Remember to adjust the configurations and code examples according to your specific Symfony project structure and requirements.


.

**Comment by DevCEDTeam** [comment]
4. Configure your application's security.yml:
   - Open the `app/config/security.yml` file.
   - Add the following configuration for the FOSOAuthServerBundle:
     ```yaml
     security:
         firewalls:
             oauth_token:
                 pattern:    ^/oauth/v2/token
                 security:   false
     
             oauth_authorize:
                 pattern:    ^/oauth/v2/auth
                 # Add your favorite authentication process here
     
             api:
                 pattern:    ^/api
                 fos_oauth:  true
                 stateless:  true
                 anonymous:  false # can be omitted as its default value
     
         access_control:
             - { path: ^/api, roles: [IS_AUTHENTICATED_FULLY] }
     ```
     Note: Adjust the firewall patterns (`^/oauth/v2/token`, `^/oauth/v2/auth`, `^/api`) and access control as per your project's requirements.

5. Configure FOSOAuthServerBundle:
   - Open the `app/config/routing.yml` file.
   - Import the routing configuration for the FOSOAuthServerBundle:
     ```yaml
     # app/config/routing.yml
     fos_oauth_server_token:
         resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
     
     fos_oauth_server_authorize:
         resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
     ```

   - Open the `app/config/config.yml` file.
   - Add the FOSOAuthServerBundle configuration:
    Certainly! Here's the continuation of the configuration steps:

     # app/config/config.yml
     fos_oauth_server:
         db_driver: orm # or pdo_mysql if you use MySQL
         client_class: YourBundle\Entity\Client
         access_token_class: YourBundle\Entity\AccessToken
         refresh_token_class: YourBundle\Entity\RefreshToken
         auth_code_class: YourBundle\Entity\AuthCode
         service:
             user_provider: fos_user.user_provider.username_email

6. Generate the database tables:
   - Run the following command to generate the necessary database tables for the OAuth server:
     ```shell
     php bin/console doctrine:schema:update --force
     ```

7. Create the Gmail API client:
   - Go to the Google Cloud Console (https://console.cloud.google.com/).
   - Create a new project or select an existing one.
   - Enable the Gmail API for your project.
   - Create API credentials (OAuth 2.0 client ID) for your project.
   - Download the JSON file containing the client credentials.

8. Configure the Gmail API client credentials:
   - Rename the downloaded JSON file to `client_secret.json`.
   - Move the `client_secret.json` file to the `app/` directory of your Symfony project.

9. Configure the Gmail API integration:
   - Open the `app/config/config.yml` file.
   - Add the following configuration for the Gmail API:
     ```yaml
     # app/config/config.yml
     google_api:
         client_id: Your_Client_ID
         client_secret: Your_Client_Secret
         redirect_uri: Your_Redirect_URI
         scopes:
             - https://www.googleapis.com/auth/gmail.send
     ```
     Replace `Your_Client_ID`, `Your_Client_Secret`, and `Your_Redirect_URI` with the corresponding values from the client credentials you obtained in step 7.

10. Implement the Gmail API integration:
    - In your Symfony project, create a service or class responsible for handling the Gmail API integration.
    - Use the Gmail API client library (such as `google/apiclient`) to authenticate and send emails via the Gmail API.
    - Follow the Gmail API documentation and library documentation to implement the necessary logic for sending outbound emails.

11. Test the integration:
    - Create a test route or controller action to trigger the email sending functionality.
    - Make a request to the test route and verify that the emails are being sent successfully using the Gmail API.

Remember to adjust the configurations and code examples according to your specific Symfony project structure and requirements.


.
